# Generated by Django 2.2.4 on 2019-09-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titel',
            new_name='title',
        ),
    ]
